/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package foxesandrabbits;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import java.awt.FlowLayout;

/**
 *
 * @author Robin
 */
public class FoxesRabbitsGUI extends javax.swing.JFrame {

    private JButton startButton;
    private JButton resetButton;
    private JTextField steps;
    private Simulator simulator;
    
    /**
     * Creates new form FoxesRabbitsGUI
     */
    public FoxesRabbitsGUI() {
        simulator = new Simulator();
        //simulator.resetSimulator();
        initComponents();
        setupFrame();
    }
    
    private void setupFrame()
    {
        setTitle("Foxes & Rabbits");
        JPanel contentPane = (JPanel)getContentPane();
        contentPane.setLayout(new BorderLayout(5, 5));
        
        //Setup of the north-area
        JPanel northPanel = createNorthPanel();
        
        
        contentPane.add(northPanel, BorderLayout.NORTH);
        contentPane.add(simulator, BorderLayout.CENTER);
        
        //Event handlers
        startButton.addActionListener(new ActionListener()
        {
            public void actionPerformed(ActionEvent e)
            {
                int numberOfSteps = Integer.parseInt(steps.getText());
                simulator.simulate(numberOfSteps);
                //simulator.runLongSimulation();
            }
        });
        
        resetButton.addActionListener(new ActionListener()
        {
            public void actionPerformed(ActionEvent e)
            {
                simulator.resetSimulator();
            }
        });
        
        pack();
        setSize(1000, 1000);
    }
    
    private JPanel createNorthPanel()
    {
        JPanel northPanel = new JPanel();
        FlowLayout northLayout = new FlowLayout();
        northPanel.setLayout(northLayout);
        
        startButton = new JButton("Start");
        startButton.setSize(new Dimension(73, 23));
        northPanel.add(startButton);
        
        resetButton = new JButton("Reset");
        resetButton.setSize(new Dimension(73, 23));
        northPanel.add(resetButton);
        
        northPanel.add(new JLabel("Aantal Stappen:"));
        
        steps = new JTextField(10);
        steps.setSize(new Dimension(6, 20));
        northPanel.add(steps);
        
        return northPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FoxesRabbitsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FoxesRabbitsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FoxesRabbitsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FoxesRabbitsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FoxesRabbitsGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
